name: webui
on:
  push:
    paths:
      - 'webui/**'
    branches:
      - master
      - main
env:
  IMAGE_NAME: gebug-webui

jobs:
  dockerhub:
    name: Push Web UI Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v6
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: gebug
          password: ${{ secrets.DOCKERHUB_PASS }}
      - name: Build & Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: webui/Dockerfile
          push: true
          tags: gebug/webui:latest